/**
 * Product data model for Day Day Ceramics.
 *
 * Kept intentionally data-driven so the same shape can later be hydrated from
 * Shopify: every product carries `shopifyProductId` / `shopifyVariantId` hooks
 * (null for now) and the grid/detail routes read only from these helpers.
 *
 * IMAGES (temporary demo): per-product photos haven't been imported yet, so
 * every product shares ONE hero photo (`/images/products/feature.webp`) and ONE
 * color turntable spin (`/images/spin/cup-a`) on hover. This is intentional
 * until the asset pipeline imports real per-product assets, at which point each
 * product's `defaultImage` / `alternateImage` / `spinMedia` / `hoverType` will
 * be replaced individually. `PLACEHOLDER_IMAGE` is retained for reference.
 */

import generatedAssetOverrides from "./product-assets.generated.json";
import { getRuntimeSoldSlugs } from "./sold-store";

/** Centralized placeholder image — replace per product once real photos exist. */
export const PLACEHOLDER_IMAGE = "/images/tea-cup.png";

export type HoverType = "staticOnly" | "alternateAngle" | "spin360";

/**
 * Product categories. An INTERNAL tag only — collection pages render a single
 * flat grid each and never show category section headers. Category is used to
 * organize the asset drop zone (`assets-incoming/<collection>/<category>/...`)
 * and is available on every product for future filtering/SEO.
 */
export const CATEGORIES: { slug: string; label: string }[] = [
  { slug: "bowls", label: "Bowls" },
  { slug: "cups", label: "Cups" },
  { slug: "mugs", label: "Mugs" },
  { slug: "coffee-drippers", label: "Coffee Drippers" },
  { slug: "plates", label: "Plates" },
  { slug: "objects", label: "Objects" },
];

/** Resolve a human label from a category slug (falls back to the slug). */
export function categoryLabel(slug: string): string {
  return CATEGORIES.find((c) => c.slug === slug)?.label ?? slug;
}

export type Product = {
  id: string;
  slug: string;
  title: string;
  /** Internal category tag (one of CATEGORIES[].slug). Not shown as sections. */
  category: string;
  /** Price in whole currency units (USD). Ignored for display when isSold. */
  price: number;
  isSold: boolean;
  /** Static image always shown by default. */
  defaultImage: string;
  /**
   * Ordered list of detail-page photo URLs (the full product gallery). These
   * KEEP their original background (unlike the matted `defaultImage`/spin) and
   * are rendered as a gallery on the product detail page. Empty by default;
   * populated by the asset importer for zip/gallery pieces.
   */
  detailImages: string[];
  /**
   * Ordered list of EXTRA detail-page video URLs (web mp4). The piece's primary
   * 360 turntable becomes the `spinMedia` spin; any additional clips that ship
   * with the piece are surfaced here and rendered as inline muted players on the
   * detail page so nothing from the drop is dropped. Empty by default; populated
   * by the asset importer for zip pieces with more than one video.
   */
  detailVideos: string[];
  hoverType: HoverType;
  /** Second angle for `alternateAngle` crossfade. null otherwise. */
  alternateImage: string | null;
  /**
   * Base path (directory) for a 360 spin asset for `spin360`. A real pipeline
   * will later drop a `manifest.json` + frames here under /public/images/spin.
   * The grid component fetches the manifest and gracefully falls back to
   * `defaultImage` when the asset is missing/unavailable. null otherwise.
   */
  spinMedia: string | null;
  /** Shopify wiring — null until catalog is connected. */
  shopifyProductId: string | null;
  shopifyVariantId: string | null;
};

export type Collection = {
  slug: string;
  title: string;
  tagline: string;
  products: Product[];
};

/**
 * Folder-generated catalog layer, keyed by `"<collection-slug>/<piece-slug>"`.
 *
 * GENERATED by `tools/asset-pipeline/import.mjs` (`npm run import-assets`) into
 * `product-assets.generated.json`. Empty (a no-op) until real pieces are
 * imported. Each entry is a FULL piece record derived from the drop-zone folder
 * tree (`assets-incoming/<collection>/<category>/<piece>/`): `category` +
 * `title` (from the piece folder name) + resolved asset paths, plus the
 * preserved `price`/`isSold` (defaults 0/false, never clobbered across runs).
 *
 * Two roles, both non-destructive (see `buildCollections`):
 *  - For a piece that ALSO exists in the hand-authored seed below, it supplies
 *    `category` + asset fields (the human-edited `price`/`isSold`/`shopify*`/
 *    `title` stay authoritative).
 *  - For a piece NOT in the seed, it is APPENDED as a brand-new product in its
 *    collection's flat grid.
 */
type GeneratedPiece = {
  category?: string;
  title?: string;
  defaultImage?: string;
  alternateImage?: string | null;
  spinMedia?: string | null;
  detailImages?: string[];
  detailVideos?: string[];
  hoverType?: HoverType;
  price?: number;
  isSold?: boolean;
};

const generatedPieces = generatedAssetOverrides as unknown as Record<
  string,
  GeneratedPiece
>;

/** Title-case a kebab slug, e.g. `ramen-bowl-blue` -> "Ramen Bowl Blue". */
export function humanizeSlug(slug: string): string {
  return slug
    .split("-")
    .filter(Boolean)
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

/** Hand-authored catalog. Asset fields are layered on via `assetOverrides`. */
const baseCollections: Collection[] = [
  {
    slug: "darling-babies",
    title: "Darling Babies",
    tagline: "Everyday pieces for the table — thrown, trimmed, and glazed by hand.",
    // Real imported pieces only — every entry's assets (defaultImage /
    // spinMedia / detailImages / detailVideos / hoverType / category) are
    // supplied by the generated layer (`product-assets.generated.json`) via
    // `buildCollections`. Prices stay 0 placeholders until edited. Order is
    // authored here: raku-white-bowl leads, then the other objects, then the
    // mug, then the cup.
    products: [
      {
        id: "raku-white-bowl",
        slug: "raku-white-bowl",
        title: "Raku White Bowl",
        category: "objects",
        price: 35,
        isSold: true,
        defaultImage: "/images/products/feature.webp",
        detailImages: [],
        detailVideos: [],
        hoverType: "spin360",
        alternateImage: null,
        spinMedia: "/images/spin/cup-a",
        shopifyProductId: null,
        shopifyVariantId: null,
      },
      {
        id: "apple-melted",
        slug: "apple-melted",
        title: "Apple Melted",
        category: "objects",
        price: 85,
        isSold: true,
        defaultImage: "/images/products/feature.webp",
        detailImages: [],
        detailVideos: [],
        hoverType: "spin360",
        alternateImage: null,
        spinMedia: "/images/spin/cup-a",
        shopifyProductId: null,
        shopifyVariantId: null,
      },
      {
        id: "raku-blue-holder",
        slug: "raku-blue-holder",
        title: "Raku Blue Holder",
        category: "objects",
        price: 28,
        isSold: false,
        defaultImage: "/images/products/feature.webp",
        detailImages: [],
        detailVideos: [],
        hoverType: "spin360",
        alternateImage: null,
        spinMedia: "/images/spin/cup-a",
        shopifyProductId: null,
        shopifyVariantId: null,
      },
      {
        id: "apple-with-a-hole",
        slug: "apple-with-a-hole",
        title: "Apple With A Hole",
        category: "objects",
        price: 85,
        isSold: false,
        defaultImage: "/images/products/feature.webp",
        detailImages: [],
        detailVideos: [],
        hoverType: "spin360",
        alternateImage: null,
        spinMedia: "/images/spin/cup-a",
        shopifyProductId: null,
        shopifyVariantId: null,
      },
      {
        id: "blue-vase",
        slug: "blue-vase",
        title: "Blue Vase",
        category: "objects",
        price: 35,
        isSold: true,
        defaultImage: "/images/products/feature.webp",
        detailImages: [],
        detailVideos: [],
        hoverType: "spin360",
        alternateImage: null,
        spinMedia: "/images/spin/cup-a",
        shopifyProductId: null,
        shopifyVariantId: null,
      },
      {
        id: "apple-peeled",
        slug: "apple-peeled",
        title: "Apple Peeled",
        category: "objects",
        price: 65,
        isSold: true,
        defaultImage: "/images/products/feature.webp",
        detailImages: [],
        detailVideos: [],
        hoverType: "spin360",
        alternateImage: null,
        spinMedia: "/images/spin/cup-a",
        shopifyProductId: null,
        shopifyVariantId: null,
      },
      {
        id: "mug-with-half-heart-handle",
        slug: "mug-with-half-heart-handle",
        title: "Mug With Half Heart Handle",
        category: "mugs",
        price: 0,
        isSold: true,
        defaultImage: "/images/products/feature.webp",
        detailImages: [],
        detailVideos: [],
        hoverType: "spin360",
        alternateImage: null,
        spinMedia: "/images/spin/cup-a",
        shopifyProductId: null,
        shopifyVariantId: null,
      },
    ],
  },
  {
    slug: "ugly-babies",
    title: "Ugly Babies",
    tagline: "Sculptural vessels for stems, branches, and quiet corners.",
    // No hand-authored seed pieces: every ugly-babies piece (green-celadon
    // tasting cup + snow cup moved here from darling, plus the raku yellow ash
    // tray) is supplied entirely by the generated layer and APPENDED here by
    // `buildCollections`. These are "adopt" pieces — shown without a price.
    products: [],
  },
];

/**
 * Merge the folder-generated layer onto the hand-authored seed catalog,
 * non-destructively, unioned by `"<collection>/<slug>"`:
 *
 *  1. For each SEED product, a matching generated entry supplies `category` +
 *     asset fields (`defaultImage` / `alternateImage` / `spinMedia` /
 *     `hoverType`). Human-edited fields (`price`, `isSold`, `shopify*`, and
 *     `title`) stay authoritative on the seed.
 *  2. Generated entries with NO matching seed product are APPENDED as new
 *     products in their collection's flat grid (price/sold default to the
 *     preserved values the importer wrote, 0/false until edited).
 *
 * With an empty generated map this returns the seed catalog unchanged.
 */
function buildCollections(
  cols: Collection[],
  generated: Record<string, GeneratedPiece>
): Collection[] {
  const seedKeys = new Set<string>();
  for (const c of cols) {
    for (const p of c.products) seedKeys.add(`${c.slug}/${p.slug}`);
  }

  const result: Collection[] = cols.map((collection) => ({
    ...collection,
    products: collection.products.map((product) => {
      const g = generated[`${collection.slug}/${product.slug}`];
      if (!g) return product;
      return {
        ...product,
        category: g.category ?? product.category,
        defaultImage: g.defaultImage ?? product.defaultImage,
        alternateImage:
          g.alternateImage !== undefined
            ? g.alternateImage
            : product.alternateImage,
        spinMedia:
          g.spinMedia !== undefined ? g.spinMedia : product.spinMedia,
        detailImages:
          g.detailImages !== undefined ? g.detailImages : product.detailImages,
        detailVideos:
          g.detailVideos !== undefined ? g.detailVideos : product.detailVideos,
        hoverType: g.hoverType ?? product.hoverType,
      };
    }),
  }));

  for (const key of Object.keys(generated)) {
    if (seedKeys.has(key)) continue;
    const slash = key.indexOf("/");
    if (slash <= 0) continue;
    const collectionSlug = key.slice(0, slash);
    const slug = key.slice(slash + 1);
    const collection = result.find((c) => c.slug === collectionSlug);
    if (!collection) continue; // unknown collection — ignore
    const g = generated[key];
    collection.products.push({
      id: `${collectionSlug}-${slug}`,
      slug,
      title: g.title ?? humanizeSlug(slug),
      category: g.category ?? "",
      price: g.price ?? 0,
      isSold: g.isSold ?? false,
      defaultImage: g.defaultImage ?? PLACEHOLDER_IMAGE,
      detailImages: g.detailImages ?? [],
      detailVideos: g.detailVideos ?? [],
      hoverType: g.hoverType ?? "staticOnly",
      alternateImage: g.alternateImage ?? null,
      spinMedia: g.spinMedia ?? null,
      shopifyProductId: null,
      shopifyVariantId: null,
    });
  }

  return result;
}

export const collections: Collection[] = buildCollections(
  baseCollections,
  generatedPieces
);

export function getCollection(slug: string): Collection | undefined {
  return collections.find((c) => c.slug === slug);
}

/**
 * A grid cell pairs a product with the collection slug it lives under, so the
 * grid can render a SINGLE flat collection or a COMBINED list of every product
 * across collections while each cell still links to its own detail route.
 */
export type ProductCellData = { product: Product; collectionSlug: string };

/**
 * Slugs hidden from ALL display surfaces (home grid, per-collection grids, and
 * the deterministic interleave) WITHOUT deleting their data/assets.
 *
 * Filtering happens in `collectionCells`, which every product list funnels
 * through (`allProductCells` builds on it), so a hidden piece disappears from
 * `/`, both collection pages, and the interleave at once. The underlying seed
 * data + imported assets stay intact, so a piece can be `getProduct`-looked-up
 * by slug if ever linked directly.
 *
 * TO UNHIDE: remove the slug from this set (one line) — nothing else changes.
 */
const HIDDEN_SLUGS = new Set<string>([
  "raku-blue-holder", // darling — temporarily hidden
  "raku-yellow-ash-tray", // ugly baby — temporarily hidden
]);

/** Cells for one collection's grid (collection page). Hidden slugs excluded. */
export function collectionCells(collection: Collection): ProductCellData[] {
  return collection.products
    .filter((product) => !HIDDEN_SLUGS.has(product.slug))
    .map((product) => ({
      product,
      collectionSlug: collection.slug,
    }));
}

/**
 * Deterministically INTERLEAVE several ordered lists into one, spreading each
 * list proportionally across the result. At every step we emit the next item
 * from whichever list is currently the FURTHEST BEHIND its proportional share
 * (`consumed / length`), with ties broken by list order. This keeps each
 * collection's own order intact while mixing them evenly — and it depends only
 * on the input lengths/order, so it is STABLE across renders (identical on the
 * server and client → no hydration mismatch, no reshuffle on refresh).
 */
function interleaveProportional<T>(lists: T[][]): T[] {
  const out: T[] = [];
  const consumed = lists.map(() => 0);
  const total = lists.reduce((n, l) => n + l.length, 0);
  for (let step = 0; step < total; step++) {
    let pick = -1;
    let bestShare = Infinity;
    for (let i = 0; i < lists.length; i++) {
      if (consumed[i] >= lists[i].length) continue;
      const share = consumed[i] / lists[i].length;
      if (share < bestShare) {
        bestShare = share;
        pick = i;
      }
    }
    out.push(lists[pick][consumed[pick]]);
    consumed[pick]++;
  }
  return out;
}

/**
 * Every product across all collections, for the combined home grid. The
 * collections are INTERLEAVED (see `interleaveProportional`) so the smaller
 * collection (e.g. the three "ugly babies") is mixed evenly through the grid
 * instead of clumping in its own trailing rows. The ordering is deterministic
 * (no `Math.random`), so it matches between SSR and the client.
 */
export function allProductCells(): ProductCellData[] {
  return interleaveProportional(
    collections.map((collection) => collectionCells(collection))
  );
}

/** Apply runtime sold overlay (Redis + baseline) onto a product copy. */
function applySoldOverlay(product: Product, soldSlugs: Set<string>): Product {
  if (product.isSold || soldSlugs.has(product.slug)) {
    return { ...product, isSold: true };
  }
  return product;
}

function collectionWithSold(
  collection: Collection,
  soldSlugs: Set<string>
): Collection {
  return {
    ...collection,
    products: collection.products.map((p) => applySoldOverlay(p, soldSlugs)),
  };
}

/** Home grid cells with live sold status (Stripe webhook + Redis). */
export async function allProductCellsLive(): Promise<ProductCellData[]> {
  const soldSlugs = await getRuntimeSoldSlugs();
  return interleaveProportional(
    collections.map((collection) =>
      collectionCells(collectionWithSold(collection, soldSlugs))
    )
  );
}

/** One collection with live sold status merged in. */
export async function getCollectionLive(
  slug: string
): Promise<Collection | undefined> {
  const data = getCollection(slug);
  if (!data) return undefined;
  const soldSlugs = await getRuntimeSoldSlugs();
  return collectionWithSold(data, soldSlugs);
}

/** Look up a product within a collection by its SLUG (not id). */
export function getProduct(collectionSlug: string, productSlug: string) {
  const collection = getCollection(collectionSlug);
  const product = collection?.products.find((p) => p.slug === productSlug);
  if (!collection || !product) return undefined;
  return { collection, product };
}

/** Formatted price label for the grid pill, e.g. "$68". */
export function priceLabel(price: number): string {
  return `$${price}`;
}
